site_name: Batch Clipboard
site_url: https://batchclipboard.bananameter.lol
repo_url: https://github.com/jpmhouston/Batch-Clipboard
repo_name: Batch Clipboard on GitHub
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to always light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to always dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to automatic light/dark mode
  features:
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.footer
      - navigation.path
      - search.highlight
      - toc.integrate
  logo: assets/logo.png
  favicon: assets/favicon.ico
  custom_dir: overrides

copyright: Copyright &copy; 2025 Bananameter Labs
extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@bananameterlabs
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/bananameterlabs.bsky.social
    - icon: fontawesome/brands/twitter
      link: http://twitter.com/bananameterlabs
    - icon: fontawesome/brands/github
      link: https://github.com/jpmhouston/Batch-Clipboard/
    - icon: fontawesome/solid/envelope
      link: mailto:info@bananameter.lol
      name: Email
    - icon: fontawesome/solid/house
      link: https://bananameter.lol
      name: Bananameter Labs homepage

plugins:
  - blog
  - search

nav:
  - About:
    - About Batch Clipboard for macOS: index.md
    - Changes-Coming-In-Version-2.0.md
  - Documentation:
    - Installing-and-Starting.md
    - The-Basics.md
    - Beyond-the-Basics.md
    - The Batch Clipboard Menu:
      - About the Batch Clipboard Menu: The-Batch-Clipboard-Menu.md
      - Menu-Icon-States.md
      - Special-Menu-Icon-Actions.md
      - Menu-Items.md
      - Batch-Mode-Menu-Items.md
      - Expanded-Menu.md
    - Settings:
      - About Settings: Settings.md
      - General-Panel.md
      - Appearance-Panel.md
      - Support-Us-Panel.md
      - Storage-Panel.md
      - Ignore-Panel.md
      - Advanced-Panel.md
    - App Store vs. GitHub Versions:
      - App-Store-Version-Differences.md
      - Bonus-Feature-Menu-Items.md
      - Start-Batch-Mode-From-History.md
      - More-Expanded-Menu-Features.md
    - Advanced:
      - Turn-Off-Clipboard-Monitoring.md
      - Ignore-Custom-Copy-Types.md
    - Privacy-Policy.md
  - Blog:
    - blog/index.md
#  - Media Materials:
#    - PR-Version-2.0.md
